# Generated by Django 6.0.2 on 2026-03-22 15:29

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name="Nom d'utilisateur")),
                ('nom', models.CharField(max_length=150, verbose_name='Nom de famille')),
                ('prenom', models.CharField(max_length=225, verbose_name='Prénom')),
                ('user_type', models.CharField(choices=[('eleve', 'Eleve'), ('formateur', 'Formateur'), ('admin', 'Administrateur')], default='eleve', max_length=20, verbose_name="Type d'utilisateur")),
                ('matricule', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Matricule')),
                ('email', models.EmailField(default='ah@gmail.com', max_length=254, unique=True, verbose_name='Adresse email')),
                ('adresse', models.CharField(max_length=225, verbose_name='Adresse')),
                ('tel', models.CharField(blank=True, max_length=25, null=True, verbose_name='Telephone')),
                ('sexe', models.CharField(choices=[('m', 'Masculin'), ('f', 'Feminin')], default='m', max_length=2, verbose_name='Sexe')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('groups', models.ManyToManyField(blank=True, help_text="Groupe  de l'utilisateur.", related_name='utilisateur_set', related_query_name='utilisateur', to='auth.group', verbose_name='Groupes')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permission specifique.', related_name='utilisateur_set', related_query_name='utilisateur', to='auth.permission', verbose_name='Permissions des utilisateurs')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Tous les utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.utilisateur')),
                ('lieu_naissance', models.CharField(max_length=225, verbose_name='Lieu de naissance')),
            ],
            options={
                'verbose_name': 'Élève',
                'verbose_name_plural': 'Élèves',
            },
            bases=('accounts.utilisateur',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.utilisateur')),
                ('emploi', models.CharField(max_length=225, verbose_name='Emploi')),
                ('specialite', models.CharField(max_length=225, verbose_name='Specialite')),
                ('date_integration', models.DateField(verbose_name="Date d'integration")),
            ],
            options={
                'verbose_name': 'Formateur',
                'verbose_name_plural': 'Formateurs',
            },
            bases=('accounts.utilisateur',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
