# Generated by Django 6.0.2 on 2026-04-01 10:19

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('courses', '0002_centreformation_parent_centreformation_tel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='user_type',
            field=models.CharField(choices=[('eleve', 'Eleve'), ('formateur', 'Formateur'), ('admin', 'Administrateur'), ('membre', 'Membre Administration')], default='eleve', max_length=20, verbose_name="Type d'utilisateur"),
        ),
        migrations.CreateModel(
            name='MembreAdministration',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.utilisateur')),
                ('emploi', models.CharField(max_length=225, verbose_name='Emploi')),
                ('categorie', models.CharField(max_length=225, verbose_name='Catégorie')),
                ('date_integration', models.DateField(auto_now_add=True, verbose_name="Date d'integration")),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres_administration', to='courses.direction_reg', verbose_name='Direction')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres_administration', to='courses.centreformation', verbose_name='Centre de formation')),
            ],
            options={
                'verbose_name': "Membre de l'administration",
                'verbose_name_plural': "Membres de l'administration",
            },
            bases=('accounts.utilisateur',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
