# Generated by Django 5.2.2 on 2026-05-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_utilisateur_user_type_membreadministration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eleve',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='eleve',
            name='numero_identifiant',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Identifiant élève'),
        ),
    ]
