# Generated by Django 5.2.1 on 2026-05-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_eleve_options_eleve_numero_identifiant'),
        ('courses', '0008_alter_filiere_duree_formation'),
    ]

    operations = [
        migrations.AddField(
            model_name='formateur',
            name='filieres',
            field=models.ManyToManyField(blank=True, related_name='formateurs', to='courses.filiere', verbose_name='Filieres dispensees'),
        ),
    ]
