# Generated by Django 5.2.1 on 2026-06-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_formateur_filieres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='user_type',
            field=models.CharField(choices=[('eleve', 'Eleve'), ('formateur', 'Formateur'), ('admin', 'Administrateur'), ('membre', 'Membre Administration'), ('dg', 'Directeur Général'), ('dir', 'Directeur Inter-régional'), ('gestionnaire', 'Gestionnaire de Centre'), ('caissier', 'Caissière / Caissier'), ('agent_comptable', 'Agent Comptable'), ('deps', 'Direction des Études, de la Planification et des Statistiques')], default='eleve', max_length=20, verbose_name="Type d'utilisateur"),
        ),
    ]
