# Generated by Django 5.2.1 on 2026-06-20 01:39

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_utilisateur_user_type'),
        ('courses', '0012_alter_filiere_nom_diplome'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirecteurInterRegional',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('est_dgp', models.BooleanField(default=False, verbose_name='Est DGP')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_interregionale', to='courses.direction_reg', verbose_name='directeurs')),
            ],
            options={
                'verbose_name': 'Directeur Inter-régional',
                'verbose_name_plural': 'Directeurs Inter-régionaux',
            },
            bases=('accounts.utilisateur',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
