# Generated by Django 6.0.4 on 2026-07-04 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_directeurinterregional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'permissions': [('gerer_agents', 'Gérer les comptes utilisateurs'), ('gerer_permissions', 'Gérer les permissions')], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Tous les utilisateurs'},
        ),
        migrations.RemoveField(
            model_name='directeurinterregional',
            name='est_dgp',
        ),
    ]
