# Generated by Django 5.2.1 on 2026-07-18 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_utilisateur_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='tel',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.RegexValidator(message="Le numéro doit être au format international avec l'indicatif du pays (ex : +226 70 00 00 00).", regex='^\\+[1-9]\\d{6,14}$')], verbose_name='Telephone'),
        ),
    ]
