# Generated by Django 5.2.1 on 2026-07-18 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_phone_validators'),
        ('courses', '0023_restructure_formateur_module_filiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formateur',
            name='filieres',
        ),
        migrations.AddField(
            model_name='formateur',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formateurs', to='courses.filiere', verbose_name='Métier dispensé'),
        ),
        migrations.AddField(
            model_name='formateur',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formateurs', to='courses.module', verbose_name='Module dispensé'),
        ),
    ]
