# Generated by Django 6.0.4 on 2026-07-23 03:02

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_restructure_formateur_module_filiere'),
        ('courses', '0025_populate_code_centre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_client', models.CharField(choices=[('personne', 'Personne physique'), ('entreprise', 'Entreprise'), ('autre', 'Autre')], max_length=20)),
                ('nom', models.CharField(blank=True, max_length=150)),
                ('prenom', models.CharField(blank=True, max_length=150)),
                ('telephone', models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator(message="Le numéro doit être au format international avec l'indicatif du pays (ex : +226 70 00 00 00).", regex='^\\+[1-9]\\d{6,14}$')])),
                ('adresse', models.CharField(max_length=255)),
                ('type_piece', models.CharField(blank=True, choices=[('cni', "Carte Nationale d'Identité"), ('passport', 'Passeport'), ('consulaire', 'Carte consulaire'), ('militaire', 'Carte militaire'), ('autre', 'Autre')], max_length=20)),
                ('numero_piece', models.CharField(blank=True, max_length=100)),
                ('raison_sociale', models.CharField(blank=True, max_length=255)),
                ('ifu', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Prestation_prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='user_type',
            field=models.CharField(choices=[('eleve', 'Eleve'), ('formateur', 'Formateur'), ('admin', 'Administrateur'), ('membre', 'Membre Administration'), ('dg', 'Directeur Général'), ('dir', 'Directeur Inter-régional'), ('gestionnaire', 'Gestionnaire de Centre'), ('caissier', 'Caissière / Caissier'), ('agent_comptable', 'Agent Comptable'), ('deps', 'Direction des Études, de la Planification et des Statistiques'), ('daf', 'Directeur Administratif et Financier')], default='eleve', max_length=20, verbose_name="Type d'utilisateur"),
        ),
        migrations.CreateModel(
            name='DAF',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_integration', models.DateField(auto_now_add=True, verbose_name="Date d'intégration")),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dafs', to='courses.centreformation', verbose_name='Centre de rattachement')),
            ],
            options={
                'verbose_name': 'Directeur Administratif et Financier',
                'verbose_name_plural': 'Directeurs Administratifs et Financiers',
            },
            bases=('accounts.utilisateur',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Facture_prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=50, unique=True)),
                ('type_facture', models.CharField(choices=[('proforma', 'Proforma'), ('definitive', 'Définitive')], max_length=20)),
                ('objet', models.CharField(max_length=255)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='accounts.client_prestation')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures_prestation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facture de prestation',
                'verbose_name_plural': 'Factures de prestation',
                'permissions': [('gerer_facturation', 'Créer/gérer les factures de prestation'), ('valider_facture_prestation', 'Valider une facture proforma en définitive')],
            },
        ),
        migrations.CreateModel(
            name='LigneFacture_prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='accounts.facture_prestation')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.prestation_prestation')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement_prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recu', models.CharField(max_length=50, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode_paiement', models.CharField(choices=[('espece', 'Espèces'), ('mobile_money', 'Mobile Money'), ('virement', 'Virement'), ('cheque', 'Chèque')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('caissier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='accounts.facture_prestation')),
            ],
            options={
                'verbose_name': 'Paiement de prestation',
                'verbose_name_plural': 'Paiements de prestation',
                'permissions': [('encaisser_prestation', 'Encaisser un paiement de prestation')],
            },
        ),
        migrations.CreateModel(
            name='LignePaiement_prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ligne_facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.lignefacture_prestation')),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='accounts.paiement_prestation')),
            ],
        ),
    ]
