# Generated by Django 6.0.4 on 2026-08-05 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_client_prestation_prestation_prestation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='nationalite',
            field=models.CharField(blank=True, default='Burkinabè', max_length=100, null=True, verbose_name='Nationalité'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='niveau_scolaire',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Niveau scolaire'),
        ),
    ]
