# Generated by Django 6.0.4 on 2026-08-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_eleve_nationalite_eleve_niveau_scolaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='user_type',
            field=models.CharField(choices=[('eleve', 'Eleve'), ('formateur', 'Formateur'), ('admin', 'Administrateur'), ('membre', 'Membre Administration'), ('dg', 'Directeur Général'), ('dir', 'Directeur Inter-régional'), ('gestionnaire', 'Directeur de Centre'), ('caissier', 'Caissière / Caissier'), ('agent_comptable', 'Agent Comptable'), ('deps', 'Direction des Études, de la Planification et des Statistiques'), ('daf', 'Directeur Administratif et Financier')], default='eleve', max_length=20, verbose_name="Type d'utilisateur"),
        ),
    ]
