# Generated by Django 5.2.1 on 2026-08-10 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_utilisateur_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eleve',
            options={'permissions': [('gerer_eleves', 'Gérer les comptes apprenants')], 'verbose_name': 'Élève', 'verbose_name_plural': 'Élèves'},
        ),
    ]
