# Generated by Django 5.2.1 on 2026-08-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_add_parents_and_nip_to_eleve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='numero_identifiant',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Identifiant élève'),
        ),
    ]
