# Generated by Django 5.2.1 on 2026-08-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_eleve_numero_identifiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='date_etablissement_document',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'établissement du document"),
        ),
        migrations.AddField(
            model_name='eleve',
            name='numero_document',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro du document'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='type_document',
            field=models.CharField(blank=True, choices=[('acte_naissance', 'Acte de naissance'), ('cni', "Carte d'identité"), ('permis', 'Permis de conduire'), ('passeport', 'Passeport'), ('carte_militaire', 'Carte militaire'), ('carte_consulaire', 'Carte consulaire'), ('autre', 'Autre')], help_text='Requis si mineur, ou majeur avec un indicatif téléphonique autre que +226.', max_length=20, null=True, verbose_name="Type de document d'identité"),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='nip',
            field=models.CharField(blank=True, help_text='Obligatoire à partir de 18 ans, pour un numéro de téléphone burkinabè (+226).', max_length=20, null=True, verbose_name="NIP (Numéro d'Identification Personnel)"),
        ),
    ]
