# Generated by Django 6.1 on 2026-08-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_eleve_date_etablissement_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='a_handicap',
            field=models.BooleanField(default=False, verbose_name='En situation de handicap'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='piece_jointe_handicap',
            field=models.FileField(blank=True, null=True, upload_to='eleves/handicap/', verbose_name="Pièce jointe (Attestation/Certificat d'indigence)"),
        ),
        migrations.AddField(
            model_name='eleve',
            name='type_handicap',
            field=models.CharField(blank=True, choices=[('moteur', 'Handicap moteur'), ('sensoriel_visuel', 'Handicap sensoriel — Visuel'), ('sensoriel_auditif', 'Handicap sensoriel — Auditif'), ('maladie_epilepsie', 'Maladie invalidante — Épilepsie'), ('maladie_asthme', 'Maladie invalidante — Asthme'), ('autre', 'Autres maladies')], max_length=30, null=True, verbose_name='Type de handicap'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='nip',
            field=models.CharField(blank=True, help_text='Champ historique, non utilisé pour les nouvelles inscriptions.', max_length=20, null=True, verbose_name="NIP (Numéro d'Identification Personnel)"),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='type_document',
            field=models.CharField(blank=True, choices=[('extrait_naissance', 'Extrait de naissance'), ('jugement_supletif', 'Jugement supplétif')], max_length=20, null=True, verbose_name="Type de document d'identité"),
        ),
    ]
