# Generated by Django 6.1 on 2026-08-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_eleve_a_handicap_eleve_piece_jointe_handicap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Adresse email'),
        ),
    ]
