# Generated by Django 6.1 on 2026-08-21 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_utilisateur_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='piece_jointe_handicap',
            field=models.FileField(blank=True, null=True, upload_to='eleves/handicap/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name="Pièce jointe (Attestation/Certificat d'indigence)"),
        ),
    ]
