# Generated by Django 6.1 on 2026-08-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_eleve_piece_jointe_handicap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='sexe',
            field=models.CharField(choices=[('m', 'Masculin'), ('f', 'Féminin')], default='m', max_length=2, verbose_name='Sexe'),
        ),
    ]
