# Generated by Django 6.1 on 2026-08-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_utilisateur_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement_prestation',
            name='mode_paiement',
            field=models.CharField(choices=[('espece', 'Espèces'), ('mobile_money', 'Mobile Money'), ('virement', 'Virement'), ('cheque', 'Chèque')], default='espece', max_length=20),
        ),
    ]
