# Generated by Django 6.1 on 2026-08-23 20:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_eleve_niveau_scolaire'),
        ('courses', '0044_alter_paiement_mode_paiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueConnexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name="Nom d'utilisateur")),
                ('nom_complet', models.CharField(blank=True, max_length=250, verbose_name='Nom complet')),
                ('type_evenement', models.CharField(choices=[('connexion', 'Connexion'), ('deconnexion', 'Déconnexion')], max_length=20, verbose_name='Événement')),
                ('date_evenement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et heure')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.centreformation', verbose_name='Centre')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_connexions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Historique de connexion',
                'verbose_name_plural': 'Historique des connexions',
                'ordering': ['-date_evenement'],
                'permissions': [('voir_historique_connexion', "Voir l'historique des connexions")],
            },
        ),
    ]
