# Generated by Django 6.1 on 2026-08-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_historiqueconnexion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiqueconnexion',
            name='est_apprenant',
            field=models.BooleanField(default=False, verbose_name='Apprenant'),
        ),
    ]
