# Generated by Django 6.1 on 2026-08-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_historiqueconnexion_est_apprenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='niveau_scolaire',
            field=models.CharField(blank=True, choices=[('cp1', 'CP1'), ('cp2', 'CP2'), ('ce1', 'CE1'), ('ce2', 'CE2'), ('cm1', 'CM1'), ('cm2', 'CM2'), ('6e', '6ème'), ('5e', '5ème'), ('4e', '4ème'), ('3e', '3ème'), ('2nde', '2nde'), ('1ere', '1ère'), ('terminale', 'Terminale'), ('licence', 'Licence'), ('maitrise', 'Maîtrise')], max_length=150, null=True, verbose_name='Niveau scolaire'),
        ),
    ]
