# Generated by Django 6.0.2 on 2026-03-22 15:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_anne', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': "L' année scolaire  ",
            },
        ),
        migrations.CreateModel(
            name='CentreFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Creer le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifier le')),
                ('nom_centre', models.CharField(max_length=225, unique=True, verbose_name='Nom du centre')),
                ('niveau_centre', models.IntegerField(verbose_name='Niveau du centre')),
                ('adresse', models.CharField(max_length=225, verbose_name='Adresse/localisition du centre')),
                ('ville', models.CharField(max_length=225, verbose_name='Ville du centre')),
            ],
            options={
                'verbose_name': 'Centre de formation',
                'verbose_name_plural': 'Centres de formation',
            },
        ),
        migrations.CreateModel(
            name='DG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=225, unique=True, verbose_name='Nom complet')),
                ('photo', models.ImageField(help_text='Format accepté: JPG, JPEG, PNG, WEBP', upload_to='team/dg/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Photo')),
                ('position', models.CharField(default='Directeur Général', max_length=200, verbose_name='Position')),
                ('message', models.TextField(help_text='Message inspirant ou citation du DG', verbose_name='Message/Citation')),
                ('commitment', models.TextField(blank=True, help_text="Texte court sur l'engagement", null=True, verbose_name='Engagement')),
                ('is_active', models.BooleanField(default=True, help_text="Indique si ce DG est l'actuel directeur général", verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Directeur Général',
                'verbose_name_plural': 'Directeur Général',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Creer le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifier le')),
                ('nom_filiere', models.CharField(max_length=225, unique=True, verbose_name='Nom de la filiere')),
                ('duree_formation', models.IntegerField(verbose_name='Duree de formation')),
                ('nom_diplome', models.CharField(max_length=225, verbose_name='Nom du diplome')),
                ('niveau_diplome', models.CharField(choices=[('n1', 'Niveau 1'), ('n2', 'Niveau 2'), ('n3', 'Niveau 3'), ('n4', 'Niveau 4'), ('n5', 'Niveau 5')], default='n1', max_length=30, verbose_name='Niveau du diplome')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Filiere',
                'verbose_name_plural': 'Filieres',
            },
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=225, unique=True, verbose_name='Nom complet')),
                ('photo', models.ImageField(help_text='Format accepté: JPG, JPEG, PNG, WEBP', upload_to='team/members/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Photo')),
                ('position', models.CharField(max_length=200, verbose_name='Poste/Position')),
                ('description', models.TextField(help_text="Brève description de l'expertise ou du rôle", verbose_name='Description')),
                ('order', models.IntegerField(default=0, help_text="Ordre d'apparition sur la page (plus petit = premier)", verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, help_text='Indique si ce membre est actuellement actif', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Membre de l'administration",
                'verbose_name_plural': "Membres de l'administration",
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TypeFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, verbose_name='Type de frais')),
            ],
            options={
                'verbose_name': 'Type de frais ',
            },
        ),
        migrations.CreateModel(
            name='CentreEtFiliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Rendre actif')),
                ('communique', models.FileField(blank=True, null=True, upload_to='media/communiques_filieres/', verbose_name='Communique de la formation')),
                ('annee_prog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.anneescolaire', verbose_name='Année Scolaire')),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.centreformation', verbose_name='Centre')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.filiere', verbose_name='Filiere associee')),
            ],
            options={
                'verbose_name': 'Programmer une formation',
                'verbose_name_plural': 'Programmations',
                'unique_together': {('centre', 'filiere')},
            },
        ),
        migrations.CreateModel(
            name='Direction_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Creer le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifier le')),
                ('nom_direction', models.CharField(max_length=225, unique=True, verbose_name='Nom de la direction')),
                ('chef_lieu', models.CharField(max_length=225, verbose_name='Chef-lieu')),
                ('region', models.CharField(max_length=225, verbose_name='Region')),
                ('directeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.dg', verbose_name='Directeur')),
            ],
            options={
                'verbose_name': 'Direction regionale',
                'verbose_name_plural': 'Directions regionales',
            },
        ),
        migrations.AddField(
            model_name='centreformation',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centre_formations', to='courses.direction_reg', verbose_name='Direction du centre'),
        ),
        migrations.AddField(
            model_name='centreformation',
            name='filieres',
            field=models.ManyToManyField(through='courses.CentreEtFiliere', to='courses.filiere', verbose_name='Filieres'),
        ),
        migrations.CreateModel(
            name='Frais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Creer le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifier le')),
                ('montant', models.FloatField(verbose_name='Motant')),
                ('formation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.centreetfiliere', verbose_name='Formations')),
                ('type_frais', models.ForeignKey(default='Scolarité', on_delete=django.db.models.deletion.CASCADE, to='courses.typefrais', verbose_name='Frais')),
            ],
            options={
                'verbose_name': 'Frais',
                'verbose_name_plural': 'Frais',
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('statut', models.CharField(choices=[('en_cours', 'En cours de traitement'), ('valide', 'Validé - Non payé'), ('valide_paye', 'Validé et payé avec succès'), ('rejete', 'Rejeté')], default='en_cours', max_length=30, verbose_name="Statut de l'inscription")),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('motif_rejet', models.TextField(blank=True, null=True)),
                ('annee_scolaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.anneescolaire', verbose_name='Annee scolaire')),
                ('eleve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Eleve')),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.centreetfiliere', verbose_name='Formation')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'unique_together': {('formation', 'eleve')},
            },
        ),
        migrations.CreateModel(
            name='Dette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.FloatField(verbose_name='Montant total lié au type de frais')),
                ('etat_dette', models.CharField(choices=[('non_soldé', 'Non soldé'), ('soldé', 'Soldée')], default='non_soldé', max_length=20)),
                ('date_echeance', models.DateTimeField(blank=True, null=True)),
                ('frais_formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.frais', verbose_name='Frais de la formation')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettes', to='courses.inscription', verbose_name='Inscription')),
            ],
            options={
                'verbose_name': "Dette lié a l'inscription d'un apprenant",
                'verbose_name_plural': "Dettes liées à l'inscription d'un apprenant",
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Creer le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifier le')),
                ('nom_module', models.CharField(max_length=225, verbose_name='Nom du module')),
                ('volume_h_cours', models.IntegerField(verbose_name="Volume d'heure")),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.filiere', verbose_name='Filiere')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Creer le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifier le')),
                ('libelle_cours', models.CharField(max_length=225, verbose_name='Libelle du cours')),
                ('volume_h_cours', models.CharField(max_length=225, verbose_name="Volume d'heure")),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.module', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_paiement', models.FloatField(verbose_name='Montant')),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de Paiement')),
                ('mode_paiement', models.CharField(choices=[('cash', 'Cash'), ('mobile', 'Mobile')], default='mobile', max_length=30, verbose_name='Mode de paiement')),
                ('tranche', models.IntegerField(verbose_name='Tranche de paiement')),
                ('numero_quittance', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Numéro de quittance')),
                ('dette', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='courses.dette', verbose_name='Dettes')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
        migrations.CreateModel(
            name='PieceJointeInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_piece', models.CharField(max_length=225, verbose_name='Libelle de la piece')),
                ('type_piece', models.CharField(choices=[('type_1', 'CNIB'), ('type_2', 'BULLETIN'), ('type_3', 'PHOTO')], default='type_1', max_length=30, verbose_name='Type de piece')),
                ('est_requis', models.BooleanField(default=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.centreetfiliere', verbose_name='Formation')),
            ],
            options={
                'verbose_name': "Piece jointe de l'inscription",
                'verbose_name_plural': "Pieces jointe de l'inscription",
            },
        ),
        migrations.CreateModel(
            name='DocumentEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece', models.FileField(blank=True, null=True, upload_to='eleves/pieces', verbose_name='Fichier')),
                ('date_depot', models.DateTimeField(blank=True, null=True, verbose_name='Date de depot')),
                ('inscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.inscription', verbose_name='Inscriptions')),
                ('piece_requise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.piecejointeinscription', verbose_name='Documents requis')),
            ],
        ),
    ]
