# Generated by Django 6.0.2 on 2026-04-01 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centreformation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centre_enfants', to='courses.centreformation', verbose_name='Centre parent'),
        ),
        migrations.AddField(
            model_name='centreformation',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone du centre'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours de traitement'), ('valide', 'Validé - Non payé'), ('Valide', 'Validé-partiellement payé '), ('valide_paye', 'Validé et payé avec succès'), ('rejete', 'Rejeté')], default='en_cours', max_length=30, verbose_name="Statut de l'inscription"),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(choices=[('chèque', 'Chèque'), ('mobile', 'Mobile')], default='mobile', max_length=30, verbose_name='Mode de paiement'),
        ),
    ]
