# Generated by Django 6.0.4 on 2026-04-08 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_utilisateur_user_type_membreadministration'),
        ('courses', '0002_centreformation_parent_centreformation_tel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='eleve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.eleve', verbose_name='Eleve'),
        ),
    ]
