# Generated by Django 5.2.2 on 2026-05-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_inscription_eleve'),
    ]

    operations = [
        migrations.AddField(
            model_name='centreetfiliere',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='centreetfiliere',
            name='date_lancement',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
