# Generated by Django 5.2.2 on 2026-05-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_centreetfiliere_date_fin_and_more'),
    ]

    operations = [
    ]
