# Generated by Django 5.2.1 on 2026-05-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_paiement_cree_par_paiement_effectue_par'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centreformation',
            name='niveau_centre',
            field=models.IntegerField(blank=True, null=True, verbose_name='Niveau du centre'),
        ),
    ]
