# Generated by Django 5.2.1 on 2026-05-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_centreformation_niveau_centre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filiere',
            name='duree_formation',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duree de formation'),
        ),
    ]
