# Generated by Django 5.2.1 on 2026-05-13 00:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_filiere_duree_formation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centreetfiliere',
            name='date_lancement',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date de lancement'),
        ),
    ]
