# Generated by Django 5.2.1 on 2026-05-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_centreetfiliere_date_lancement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centreetfiliere',
            name='communique',
            field=models.FileField(blank=True, null=True, upload_to='communiques_filieres/', verbose_name='Communique de la formation'),
        ),
        migrations.AlterField(
            model_name='piecejointeinscription',
            name='type_piece',
            field=models.CharField(choices=[('type_1', 'CNIB'), ('type_2', 'BULLETIN'), ('type_3', 'PHOTO'), ('type_4', 'Identification'), ('type_5', 'Diplome/Attestation')], default='type_1', max_length=30, verbose_name='Type de piece'),
        ),
    ]
