# Generated by Django 5.2.1 on 2026-06-16 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_centreetfiliere_communique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Creer le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifier le')),
                ('nom_province', models.CharField(max_length=225, unique=True, verbose_name='Nom de la province')),
                ('chef_lieu', models.CharField(max_length=225, verbose_name='Chef-lieu')),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Creer le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifier le')),
                ('nom_region', models.CharField(max_length=225, unique=True, verbose_name='Nom de la région')),
                ('chef_lieu', models.CharField(max_length=225, verbose_name='Chef-lieu')),
            ],
            options={
                'verbose_name': 'Région',
                'verbose_name_plural': 'Régions',
            },
        ),
        migrations.AddField(
            model_name='centreetfiliere',
            name='type_formation',
            field=models.CharField(blank=True, choices=[('initiale', 'Initiale'), ('continue', 'Continue'), ('modulaire_qualifiante', 'Modulaire qualifiante')], max_length=30, null=True, verbose_name='Type de formation'),
        ),
        migrations.AddField(
            model_name='filiere',
            name='titre_professionnel',
            field=models.CharField(blank=True, choices=[('CQP', 'Certificat de Qualification Professionnelle'), ('BQP', 'Brevet de Qualification Professionnelle'), ('BPT', 'Brevet Professionnel de Technicien'), ('BPTS', 'Brevet Professionnel de Technicien Supérieur')], max_length=10, null=True, verbose_name='Titre professionnel'),
        ),
        migrations.AlterField(
            model_name='centreformation',
            name='adresse',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Adresse/localisition du centre'),
        ),
        migrations.AlterField(
            model_name='centreformation',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centre_formations', to='courses.direction_reg', verbose_name='Direction du centre'),
        ),
        migrations.AlterField(
            model_name='centreformation',
            name='ville',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Ville du centre'),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='niveau_diplome',
            field=models.TextField(blank=True, null=True, verbose_name='Niveau du diplome'),
        ),
        migrations.AddField(
            model_name='centreformation',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centre_formations', to='courses.province', verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='province',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='courses.region', verbose_name='Région'),
        ),
    ]
