# Generated by Django 5.2.1 on 2026-06-18 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_province_region_centreetfiliere_type_formation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filiere',
            name='nom_diplome',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Nom du diplome'),
        ),
    ]
