# Generated by Django 6.0.4 on 2026-07-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_filiere_nom_diplome'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiere',
            name='texte_defilante',
            field=models.TextField(blank=True, null=True, verbose_name='Texte défilant'),
        ),
    ]
