# Generated by Django 6.0.4 on 2026-07-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_filiere_texte_defilante'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionsPlateforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('voir_statistiques', 'Voir les statistiques'), ('exporter_donnees', 'Exporter des données (CSV/Excel/PDF)')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='anneescolaire',
            options={'permissions': [('gerer_annees', 'Gérer les années scolaires')], 'verbose_name': "L' année scolaire  "},
        ),
        migrations.AlterModelOptions(
            name='centreetfiliere',
            options={'permissions': [('gerer_programmations', 'Gérer les associations centre-métier')], 'verbose_name': 'Programmer une formation', 'verbose_name_plural': 'Programmations'},
        ),
        migrations.AlterModelOptions(
            name='centreformation',
            options={'permissions': [('gerer_centres', 'Créer/modifier/supprimer un centre de formation')], 'verbose_name': 'Centre de formation', 'verbose_name_plural': 'Centres de formation'},
        ),
        migrations.AlterModelOptions(
            name='direction_reg',
            options={'permissions': [('gerer_directions', 'Créer/modifier/supprimer une direction inter-régionale')], 'verbose_name': 'Direction regionale', 'verbose_name_plural': 'Directions regionales'},
        ),
        migrations.AlterModelOptions(
            name='filiere',
            options={'permissions': [('gerer_metiers', 'Créer/modifier/supprimer un métier')], 'verbose_name': 'Filiere', 'verbose_name_plural': 'Filieres'},
        ),
        migrations.AlterModelOptions(
            name='frais',
            options={'permissions': [('gerer_frais', 'Gérer les frais et types de frais')], 'verbose_name': 'Frais', 'verbose_name_plural': 'Frais'},
        ),
        migrations.AlterModelOptions(
            name='inscription',
            options={'permissions': [('voir_inscriptions', 'Voir les candidatures'), ('valider_inscription', 'Valider une candidature'), ('rejeter_inscription', 'Rejeter une candidature')], 'verbose_name': 'Inscription', 'verbose_name_plural': 'Inscriptions'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'permissions': [('gerer_modules', 'Gérer les modules et cours')], 'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
        migrations.AlterModelOptions(
            name='paiement',
            options={'permissions': [('encaisser_paiement', 'Encaisser un paiement'), ('gerer_paiements', 'Modifier/supprimer un paiement')], 'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.AlterModelOptions(
            name='piecejointeinscription',
            options={'permissions': [('telecharger_pieces', 'Télécharger les pièces jointes des candidats')], 'verbose_name': "Piece jointe de l'inscription", 'verbose_name_plural': "Pieces jointe de l'inscription"},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'permissions': [('gerer_regions', 'Créer/modifier/supprimer une région ou province')], 'verbose_name': 'Région', 'verbose_name_plural': 'Régions'},
        ),
    ]
