# Generated by Django 5.2.1 on 2026-07-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_seed_role_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filiere',
            name='titre_professionnel',
            field=models.CharField(blank=True, choices=[('CQP', 'Certificat de Qualification Professionnelle'), ('BQP', 'Brevet de Qualification Professionnelle'), ('BPT', 'Brevet Professionnel de Technicien'), ('BPTS', 'Brevet Professionnel de Technicien Spécialiste')], max_length=10, null=True, verbose_name='Titre professionnel'),
        ),
    ]
