# Generated by Django 5.2.1 on 2026-07-12 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_filiere_titre_professionnel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together=set(),
        ),
    ]
