# Generated by Django 5.2.1 on 2026-07-13 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_inscription_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='id_inscription_rejeter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reinscriptions', to='courses.inscription', verbose_name="Inscription rejetée d'origine"),
        ),
        migrations.AddField(
            model_name='inscription',
            name='personne_contact_fonction',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonction de la personne à prévenir'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='personne_contact_nom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom de la personne à prévenir'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='personne_contact_prenom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prénom de la personne à prévenir'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='personne_contact_tel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact de la personne à prévenir'),
        ),
    ]
