# Generated by Django 5.2.1 on 2026-07-13 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_inscription_id_inscription_rejeter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrancheFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, verbose_name='Libellé de la tranche')),
                ('ordre', models.PositiveIntegerField(default=1, verbose_name='Ordre de paiement')),
                ('pourcentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pourcentage du montant total')),
                ('est_primordiale', models.BooleanField(default=False, help_text='Doit être intégralement réglée avant toute autre tranche ou tout autre type de frais.', verbose_name='Tranche primordiale')),
                ('type_frais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranches', to='courses.typefrais', verbose_name='Type de frais')),
            ],
            options={
                'verbose_name': 'Tranche de frais',
                'verbose_name_plural': 'Tranches de frais',
                'ordering': ['type_frais', 'ordre'],
            },
        ),
        migrations.AddField(
            model_name='paiement',
            name='tranche_frais',
            field=models.ForeignKey(blank=True, help_text='Tranche du type de frais à laquelle ce versement est affecté (le cas échéant).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.tranchefrais', verbose_name='Tranche de frais soldée'),
        ),
        migrations.AddConstraint(
            model_name='tranchefrais',
            constraint=models.UniqueConstraint(condition=models.Q(('est_primordiale', True)), fields=('type_frais',), name='une_seule_tranche_primordiale_par_type_frais'),
        ),
    ]
