# Generated by Django 5.2.1 on 2026-07-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_tranchefrais_paiement_tranche_frais_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionsplateforme',
            options={'default_permissions': (), 'managed': False, 'permissions': [('voir_statistiques', 'Voir les statistiques'), ('exporter_donnees', 'Exporter des données (CSV/Excel/PDF)'), ('rechercher_tous_centres', 'Rechercher un apprenant dans tous les centres (paiements)')]},
        ),
    ]
