# Generated by Django 5.2.1 on 2026-07-18 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_seed_rechercher_tous_centres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centreformation',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Le numéro doit être au format international avec l'indicatif du pays (ex : +226 70 00 00 00).", regex='^\\+[1-9]\\d{6,14}$')], verbose_name='Numéro de téléphone du centre'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='personne_contact_tel',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message="Le numéro doit être au format international avec l'indicatif du pays (ex : +226 70 00 00 00).", regex='^\\+[1-9]\\d{6,14}$')], verbose_name='Contact de la personne à prévenir'),
        ),
    ]
