# Generated by Django 5.2.1 on 2026-07-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_add_phone_validators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='filiere',
        ),
        migrations.AddField(
            model_name='filiere',
            name='curricula',
            field=models.FileField(blank=True, null=True, upload_to='curricula_filieres/', verbose_name='Curricula (programme de formation)'),
        ),
        migrations.AddField(
            model_name='module',
            name='filieres',
            field=models.ManyToManyField(blank=True, related_name='modules', to='courses.filiere', verbose_name='Métiers'),
        ),
    ]
