# Generated by Django 6.0.4 on 2026-07-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_restructure_formateur_module_filiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='centreetfiliere',
            name='date_limite_inscription',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date limite d'inscription"),
        ),
        migrations.AddField(
            model_name='centreformation',
            name='code_centre',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Code du centre'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='motif_derogation',
            field=models.TextField(blank=True, help_text='Obligatoire si le montant versé est inférieur au montant dû pour une tranche primordiale.', null=True, verbose_name='Motif de la dérogation'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='piece_jointe_derogation',
            field=models.FileField(blank=True, null=True, upload_to='paiements/derogations/', verbose_name='Pièce jointe justificative de la dérogation'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(choices=[('chèque', 'Chèque'), ('mobile', 'Mobile Money'), ('espece', 'Espèce')], default='mobile', max_length=30, verbose_name='Mode de paiement'),
        ),
    ]
