# Generated by Django 6.0.4 on 2026-07-21 02:58

import re
import unicodedata

from django.db import migrations


def _base_code(nom_centre):
    """Dérive un code court (majuscules, sans accents ni ponctuation) à partir
    du nom du centre, ex. "Centre de Ouagadougou" -> "CENTREDEOUAGADOU"."""
    normalise = unicodedata.normalize('NFKD', nom_centre or '').encode('ascii', 'ignore').decode('ascii')
    lettres = re.sub(r'[^A-Za-z0-9]', '', normalise).upper()
    return (lettres or "CENTRE")[:8]


def populate_code_centre(apps, schema_editor):
    CentreFormation = apps.get_model('courses', 'CentreFormation')
    codes_existants = set(
        CentreFormation.objects.exclude(code_centre__isnull=True)
        .exclude(code_centre='')
        .values_list('code_centre', flat=True)
    )
    for centre in CentreFormation.objects.filter(code_centre__isnull=True).order_by('id'):
        base = _base_code(centre.nom_centre)
        code = base
        suffixe = 1
        while code in codes_existants:
            suffixe += 1
            code = f"{base[:8]}{suffixe}"
        centre.code_centre = code
        centre.save(update_fields=['code_centre'])
        codes_existants.add(code)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_centreetfiliere_date_limite_inscription_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_code_centre, noop_reverse),
    ]
