# Generated by Django 6.0.4 on 2026-08-05 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_populate_code_centre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionsplateforme',
            options={'default_permissions': (), 'managed': False, 'permissions': [('voir_statistiques', 'Voir les statistiques'), ('exporter_donnees', 'Exporter des données (CSV/Excel/PDF)'), ('rechercher_tous_centres', 'Rechercher un apprenant dans tous les centres (paiements)'), ('gerer_statistiques_reelles', 'Saisir et consulter les statistiques réelles (effectifs formés, listes nominatives)')]},
        ),
        migrations.AddField(
            model_name='inscription',
            name='mode_formation',
            field=models.CharField(blank=True, choices=[('residentielle', 'Résidentielle'), ('duale', 'Duale')], max_length=20, null=True, verbose_name='Mode de formation'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='observations_reel',
            field=models.TextField(blank=True, null=True, verbose_name='Observations (statistiques réelles)'),
        ),
        migrations.CreateModel(
            name='EffectifReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(blank=True, default='', help_text='Laisser vide pour le centre principal', max_length=150, verbose_name='Site/antenne')),
                ('effectif_hommes', models.PositiveIntegerField(default=0, verbose_name='Effectif hommes')),
                ('effectif_femmes', models.PositiveIntegerField(default=0, verbose_name='Effectif femmes')),
                ('date_maj', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effectifs_reels', to='courses.centreetfiliere', verbose_name='Formation')),
            ],
            options={
                'verbose_name': 'Effectif réel formé',
                'verbose_name_plural': 'Effectifs réels formés',
                'unique_together': {('formation', 'site')},
            },
        ),
    ]
