# Generated by Django 6.0.4 on 2026-08-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_seed_gerer_statistiques_reelles'),
    ]

    operations = [
        migrations.AddField(
            model_name='effectifreel',
            name='effectif_femmes_admis',
            field=models.PositiveIntegerField(default=0, verbose_name='Effectif femmes admises'),
        ),
        migrations.AddField(
            model_name='effectifreel',
            name='effectif_femmes_presents',
            field=models.PositiveIntegerField(default=0, verbose_name="Effectif femmes présentes à l'examen"),
        ),
        migrations.AddField(
            model_name='effectifreel',
            name='effectif_hommes_admis',
            field=models.PositiveIntegerField(default=0, verbose_name='Effectif hommes admis'),
        ),
        migrations.AddField(
            model_name='effectifreel',
            name='effectif_hommes_presents',
            field=models.PositiveIntegerField(default=0, verbose_name="Effectif hommes présents à l'examen"),
        ),
        migrations.AlterField(
            model_name='effectifreel',
            name='effectif_femmes',
            field=models.PositiveIntegerField(default=0, verbose_name='Effectif femmes inscrits'),
        ),
        migrations.AlterField(
            model_name='effectifreel',
            name='effectif_hommes',
            field=models.PositiveIntegerField(default=0, verbose_name='Effectif hommes inscrits'),
        ),
    ]
