# Generated by Django 6.0.4 on 2026-08-05 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_effectifreel_effectif_femmes_admis_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='effectifreel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='effectifreel',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='effectifs_reels', to='courses.anneescolaire', verbose_name='Année scolaire'),
        ),
        migrations.AlterUniqueTogether(
            name='effectifreel',
            unique_together={('formation', 'site', 'annee_scolaire')},
        ),
    ]
