# Generated by Django 5.2.1 on 2026-08-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_seed_permissions_dir_gestionnaire_daf'),
    ]

    operations = [
        migrations.AddField(
            model_name='effectifreel',
            name='effectif_femmes_asthme',
            field=models.PositiveIntegerField(default=0, verbose_name='Maladie invalidante — asthme (femmes)'),
        ),
        migrations.AddField(
            model_name='effectifreel',
            name='effectif_femmes_autres_maladies',
            field=models.PositiveIntegerField(default=0, verbose_name='Autres maladies — femmes'),
        ),
        migrations.AddField(
            model_name='effectifreel',
            name='effectif_femmes_epilepsie',
            field=models.PositiveIntegerField(default=0, verbose_name='Maladie invalidante — épilepsie (femmes)'),
        ),
        migrations.AddField(
            model_name='effectifreel',
            name='effectif_femmes_handicap_auditif',
            field=models.PositiveIntegerField(default=0, verbose_name='Handicap sensoriel (auditif) — femmes'),
        ),
        migrations.AddField(
            model_name='effectifreel',
            name='effectif_femmes_handicap_moteur',
            field=models.PositiveIntegerField(default=0, verbose_name='Handicap moteur — femmes'),
        ),
        migrations.AddField(
            model_name='effectifreel',
            name='effectif_femmes_handicap_visuel',
            field=models.PositiveIntegerField(default=0, verbose_name='Handicap sensoriel (visuel) — femmes'),
        ),
        migrations.AddField(
            model_name='effectifreel',
            name='effectif_hommes_asthme',
            field=models.PositiveIntegerField(default=0, verbose_name='Maladie invalidante — asthme (hommes)'),
        ),
        migrations.AddField(
            model_name='effectifreel',
            name='effectif_hommes_autres_maladies',
            field=models.PositiveIntegerField(default=0, verbose_name='Autres maladies — hommes'),
        ),
        migrations.AddField(
            model_name='effectifreel',
            name='effectif_hommes_epilepsie',
            field=models.PositiveIntegerField(default=0, verbose_name='Maladie invalidante — épilepsie (hommes)'),
        ),
        migrations.AddField(
            model_name='effectifreel',
            name='effectif_hommes_handicap_auditif',
            field=models.PositiveIntegerField(default=0, verbose_name='Handicap sensoriel (auditif) — hommes'),
        ),
        migrations.AddField(
            model_name='effectifreel',
            name='effectif_hommes_handicap_moteur',
            field=models.PositiveIntegerField(default=0, verbose_name='Handicap moteur — hommes'),
        ),
        migrations.AddField(
            model_name='effectifreel',
            name='effectif_hommes_handicap_visuel',
            field=models.PositiveIntegerField(default=0, verbose_name='Handicap sensoriel (visuel) — hommes'),
        ),
    ]
