# Generated by Django 5.2.1 on 2026-08-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_effectifreel_handicap_maladies'),
    ]

    operations = [
        migrations.AddField(
            model_name='centreetfiliere',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création'),
        ),
    ]
