# Generated by Django 5.2.1 on 2026-08-12 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_seed_gerer_eleves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenteleve',
            name='piece',
            field=models.FileField(blank=True, null=True, upload_to='eleves/pieces', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Fichier'),
        ),
    ]
