# Generated by Django 5.2.1 on 2026-08-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_seed_voir_inscriptions_agent_comptable'),
    ]

    operations = [
        migrations.AddField(
            model_name='anneescolaire',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création'),
        ),
    ]
