# Generated by Django 5.2.1 on 2026-08-13 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_merge_20260812_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filiere',
            name='duree_formation',
        ),
        migrations.AddField(
            model_name='centreetfiliere',
            name='duree_jours',
            field=models.PositiveIntegerField(blank=True, help_text='Ex : 15, 45, 270 (≈ 9 mois). La date de fin est calculée automatiquement.', null=True, verbose_name='Durée (en jours)'),
        ),
        migrations.AlterField(
            model_name='centreetfiliere',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de fin (calculée automatiquement)'),
        ),
    ]
