# Generated by Django 5.2.1 on 2026-08-14 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_rename_deps_group_to_desp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anneescolaire',
            options={'permissions': [('gerer_annees', 'Gérer les années de formation')], 'verbose_name': 'Année de formation', 'verbose_name_plural': 'Années de formation'},
        ),
        migrations.AlterField(
            model_name='centreetfiliere',
            name='annee_prog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.anneescolaire', verbose_name='Année de formation'),
        ),
        migrations.AlterField(
            model_name='effectifreel',
            name='annee_scolaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='effectifs_reels', to='courses.anneescolaire', verbose_name='Année de formation'),
        ),
    ]
