# Generated by Django 6.1 on 2026-08-19 00:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_alter_anneescolaire_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='organisation_adresse',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name="Adresse de l'organisation/parrain"),
        ),
        migrations.AddField(
            model_name='inscription',
            name='organisation_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="Email de l'organisation/parrain"),
        ),
        migrations.AddField(
            model_name='inscription',
            name='organisation_nom',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Nom de l'organisation/parrain"),
        ),
        migrations.AddField(
            model_name='inscription',
            name='organisation_tel',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message="Le numéro doit être au format international avec l'indicatif du pays (ex : +226 70 00 00 00).", regex='^\\+[1-9]\\d{6,14}$')], verbose_name="Téléphone de l'organisation/parrain"),
        ),
        migrations.AddField(
            model_name='inscription',
            name='personne_contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du parent'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='type_personne_contact',
            field=models.CharField(blank=True, choices=[('parent', 'Parent'), ('organisation', 'Organisation/Parrain'), ('les_deux', 'Parent et Organisation/Parrain')], max_length=20, null=True, verbose_name='Type de personne à prévenir'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='personne_contact_fonction',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonction du contact'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='personne_contact_nom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom du parent'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='personne_contact_prenom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prénom du parent'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='personne_contact_tel',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message="Le numéro doit être au format international avec l'indicatif du pays (ex : +226 70 00 00 00).", regex='^\\+[1-9]\\d{6,14}$')], verbose_name='Contact du parent'),
        ),
    ]
