# Generated by Django 6.1 on 2026-08-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0041_inscription_organisation_adresse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typefrais',
            name='est_frais_de_dossier',
            field=models.BooleanField(default=False, help_text="Ce type de frais doit être réglé en priorité, avant tout autre type de frais de l'inscription.", verbose_name='Frais de dossier'),
        ),
    ]
