# Generated by Django 6.1 on 2026-08-21 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0042_typefrais_est_frais_de_dossier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenteleve',
            name='piece',
            field=models.FileField(blank=True, null=True, upload_to='eleves/pieces', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='piece_jointe_derogation',
            field=models.FileField(blank=True, null=True, upload_to='paiements/derogations/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Pièce jointe justificative de la dérogation'),
        ),
    ]
