# Generated by Django 6.1 on 2026-08-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_alter_documenteleve_piece_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(choices=[('chèque', 'Chèque'), ('mobile', 'Mobile Money'), ('espece', 'Espèce')], default='espece', max_length=30, verbose_name='Mode de paiement'),
        ),
    ]
