# Generated by Django 6.1 on 2026-08-24 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0044_alter_paiement_mode_paiement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionsplateforme',
            options={'default_permissions': (), 'managed': False, 'permissions': [('voir_statistiques', 'Voir les statistiques'), ('exporter_donnees', 'Exporter des données (CSV/Excel/PDF)'), ('rechercher_tous_centres', 'Rechercher un apprenant dans tous les centres (paiements)'), ('gerer_statistiques_reelles', 'Saisir et consulter le bilan des effectifs formés (listes nominatives)')]},
        ),
    ]
