# Generated by Django 6.1 on 2026-08-24 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0046_rename_gerer_statistiques_reelles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='annule',
            field=models.BooleanField(default=False, verbose_name='Annulé'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='annule_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_annules', to=settings.AUTH_USER_MODEL, verbose_name='Annulé par'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_annulation',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'annulation"),
        ),
        migrations.AddField(
            model_name='paiement',
            name='groupe_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name="Lot d'encaissement"),
        ),
        migrations.AddField(
            model_name='paiement',
            name='motif_annulation',
            field=models.TextField(blank=True, null=True, verbose_name="Motif de l'annulation"),
        ),
    ]
