# Generated by Django 6.1 on 2026-09-05 22:23

from django.db import migrations, models


def _backfill_formation(apps, schema_editor):
    """Les programmations existantes gardent le comportement actuel :
    programme « Formation »."""
    CentreEtFiliere = apps.get_model('courses', 'CentreEtFiliere')
    CentreEtFiliere.objects.filter(type_programme__isnull=True).update(type_programme='formation')


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0048_gerer_equipe_et_validateurs_fichiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='centreetfiliere',
            name='type_programme',
            field=models.CharField(blank=True, choices=[('vacances_utiles', 'Vacances utiles'), ('formation', 'Formation'), ('reconversion', 'Reconversion')], max_length=20, null=True, verbose_name='Type de programme'),
        ),
        migrations.RunPython(_backfill_formation, migrations.RunPython.noop),
    ]
