# Generated by Django 6.1 on 2026-09-05 23:10

from django.db import migrations


# Programme Reconversion : centralisé (parcours par ville, centre masqué). Sa
# validation est réservée par défaut à l'Admin et au Directeur Général ; les
# autres rôles l'obtiennent via RH → Permissions si besoin.
GROUPES_PAR_DEFAUT = ['Admin', 'Directeur Général']


def _seed_permission(apps, schema_editor):
    from django.contrib.auth.management import create_permissions
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    perm = Permission.objects.filter(codename='valider_inscription_reconversion').first()
    if not perm:
        return
    for nom in GROUPES_PAR_DEFAUT:
        groupe, _ = Group.objects.get_or_create(name=nom)
        groupe.permissions.add(perm)


def _unseed_permission(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    perm = Permission.objects.filter(codename='valider_inscription_reconversion').first()
    if perm:
        for groupe in Group.objects.all():
            groupe.permissions.remove(perm)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0049_centreetfiliere_type_programme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscription',
            options={'permissions': [('voir_inscriptions', 'Voir les candidatures'), ('valider_inscription', 'Valider une candidature'), ('valider_inscription_reconversion', 'Valider une candidature en programme Reconversion'), ('rejeter_inscription', 'Rejeter une candidature')], 'verbose_name': 'Inscription', 'verbose_name_plural': 'Inscriptions'},
        ),
        migrations.RunPython(_seed_permission, _unseed_permission),
    ]
