# Generated by Django 6.1 on 2026-09-08 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0050_alter_inscription_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrouselAccueil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(choices=[('initiale', 'Formations initiales'), ('continue', 'Formations continues'), ('modulaire_qualifiante', 'Formations modulaires qualifiantes'), ('reconversion', 'Programme de reconversion des diplômés du système universitaire'), ('vacances_utiles', 'Programme vacances utiles avec BSB')], max_length=30, unique=True, verbose_name='Carrousel')),
                ('titre', models.CharField(blank=True, help_text='Laisser vide pour garder le titre par défaut.', max_length=120, verbose_name='Titre affiché')),
                ('image', models.ImageField(blank=True, help_text="Laisser vide pour garder l'image par défaut. JPG, JPEG, PNG ou WEBP.", null=True, upload_to='accueil/carrousel/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Image')),
                ('texte_defilant', models.CharField(blank=True, help_text="Bandeau qui défile sous l'image. Laisser vide pour n'afficher aucun bandeau.", max_length=200, verbose_name='Texte défilant')),
                ('date_maj', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Carrousel de l'accueil",
                'verbose_name_plural': "Carrousels de l'accueil",
                'ordering': ['cle'],
                'permissions': [('gerer_carrousel', "Gérer les carrousels de l'accueil")],
            },
        ),
    ]
