# Generated by Django 6.1 on 2026-09-09 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0052_seed_gerer_carrousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandeAnnonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=220, verbose_name="Texte de l'annonce")),
                ('lien', models.URLField(blank=True, help_text="URL vers laquelle pointe l'annonce.", verbose_name='Lien (facultatif)')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_maj', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Bande-annonce de l'accueil",
                'verbose_name_plural': "Bandes-annonces de l'accueil",
                'ordering': ['ordre', '-date_maj'],
            },
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom du partenaire')),
                ('logo', models.ImageField(help_text='JPG, JPEG, PNG, WEBP ou SVG. Fond transparent conseillé.', upload_to='accueil/partenaires/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg'])], verbose_name='Logo')),
                ('lien', models.URLField(blank=True, verbose_name='Site web (facultatif)')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_maj', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='carrouselaccueil',
            options={'ordering': ['cle'], 'permissions': [('gerer_carrousel', "Gérer le contenu de la page d'accueil")], 'verbose_name': "Carrousel de l'accueil", 'verbose_name_plural': "Carrousels de l'accueil"},
        ),
    ]
