# Generated by Django 6.1 on 2026-09-09 22:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0053_bandeannonce_partenaire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideUtilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil', models.CharField(choices=[('eleve', 'Apprenant (et visiteurs non connectés)'), ('formateur', 'Formateur'), ('gestionnaire', 'Directeur de Centre'), ('caissier', 'Caissière / Caissier'), ('agent_comptable', 'Agent Comptable'), ('membre', "Membre de l'administration"), ('dir', 'Directeur Inter-régional'), ('deps', 'Direction des Études, de la Planification et des Statistiques'), ('daf', 'Directeur Administratif et Financier'), ('dg', 'Directeur Général'), ('admin', 'Administrateur')], max_length=20, unique=True, verbose_name='Profil concerné')),
                ('titre', models.CharField(blank=True, help_text='Laisser vide pour un titre automatique (« Guide — <profil> »).', max_length=150, verbose_name='Titre affiché')),
                ('fichier_pdf', models.FileField(blank=True, help_text="Fichier PDF. Laisser vide s'il n'y a pas de document.", null=True, upload_to='guides/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Guide PDF')),
                ('video_url', models.URLField(blank=True, help_text="YouTube ou Vimeo (intégré directement), ou tout autre lien (ouvert dans un nouvel onglet). Laisser vide s'il n'y a pas de vidéo.", verbose_name='Lien vidéo')),
                ('actif', models.BooleanField(default=True, help_text='Décochez pour masquer temporairement le guide de ce profil.', verbose_name='Visible')),
                ('date_maj', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Guide d'utilisation",
                'verbose_name_plural': "Guides d'utilisation",
                'ordering': ['profil'],
                'permissions': [('gerer_guides', "Gérer les guides d'utilisation")],
            },
        ),
    ]
