# Generated by Django 6.1 on 2026-09-09 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0055_seed_gerer_guides'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiement',
            options={'permissions': [('encaisser_paiement', 'Encaisser un paiement'), ('gerer_paiements', 'Modifier/supprimer un paiement'), ('annuler_paiement', 'Annuler un versement encaissé')], 'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
    ]
