# Generated by Django 6.1 on 2026-09-11 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0057_seed_annuler_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frais',
            name='montant',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Motant'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant_paiement',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant'),
        ),
    ]
