# Generated by Django 6.1 on 2026-09-20 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0058_alter_frais_montant_alter_paiement_montant_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filiere',
            name='titre_professionnel',
            field=models.CharField(blank=True, choices=[('CQP', 'Certificat de Qualification Professionnelle'), ('BQP', 'Brevet de Qualification Professionnelle'), ('BPT', 'Brevet Professionnel de Technicien'), ('BPTS', 'Brevet Professionnel de Technicien Spécialisé')], max_length=10, null=True, verbose_name='Titre professionnel'),
        ),
    ]
