# Generated by Django 6.1 on 2026-09-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0059_alter_filiere_titre_professionnel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='numero_quittance',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Numéro de quittance'),
        ),
    ]
