# Generated by Django 6.1 on 2026-09-24 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0060_alter_paiement_numero_quittance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiement',
            options={'permissions': [('encaisser_paiement', 'Encaisser un paiement'), ('gerer_paiements', 'Modifier/supprimer un paiement'), ('annuler_paiement', 'Annuler un versement encaissé'), ('filtrer_historique_avance', "Filtrer l'historique des paiements par critères avancés")], 'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
    ]
