# Generated by Django 6.1 on 2026-09-24 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0061_alter_paiement_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='frais',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.centreetfiliere', verbose_name='Formations'),
        ),
        migrations.CreateModel(
            name='Hebergement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Creer le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifier le')),
                ('nombre_places', models.PositiveIntegerField(verbose_name='Nombre de places')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=10, verbose_name='Statut')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hebergements', to='courses.anneescolaire', verbose_name='Année scolaire')),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hebergements', to='courses.centreformation', verbose_name='Centre')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hebergements_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('metiers', models.ManyToManyField(blank=True, related_name='hebergements_eligibles', to='courses.centreetfiliere', verbose_name='Métiers éligibles')),
            ],
            options={
                'verbose_name': 'Hébergement',
                'verbose_name_plural': 'Hébergements',
                'permissions': [('gerer_hebergements', 'Créer/modifier/désactiver un hébergement'), ('valider_demande_hebergement', "Valider ou rejeter une demande d'hébergement")],
            },
        ),
        migrations.CreateModel(
            name='DemandeHebergement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=15, verbose_name='Statut')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de la demande')),
                ('date_decision', models.DateTimeField(blank=True, null=True, verbose_name='Date de la décision')),
                ('motif_rejet', models.TextField(blank=True, null=True, verbose_name='Motif du rejet')),
                ('decide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_hebergement_decidees', to=settings.AUTH_USER_MODEL, verbose_name='Décidé par')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_hebergement', to='courses.inscription', verbose_name='Inscription')),
                ('hebergement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='courses.hebergement', verbose_name='Hébergement')),
            ],
            options={
                'verbose_name': "Demande d'hébergement",
                'verbose_name_plural': "Demandes d'hébergement",
            },
        ),
        migrations.AddField(
            model_name='frais',
            name='hebergement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frais', to='courses.hebergement', verbose_name='Hébergement'),
        ),
        migrations.AddConstraint(
            model_name='frais',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('formation__isnull', False), ('hebergement__isnull', True)), models.Q(('formation__isnull', True), ('hebergement__isnull', False)), _connector='OR'), name='frais_formation_xor_hebergement'),
        ),
        migrations.AddConstraint(
            model_name='demandehebergement',
            constraint=models.UniqueConstraint(fields=('hebergement', 'inscription'), name='une_demande_par_inscription_et_hebergement'),
        ),
    ]
