# Generated by Django 6.1 on 2026-09-29 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0062_alter_frais_formation_hebergement_demandehebergement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscription',
            options={'permissions': [('voir_inscriptions', 'Voir les candidatures'), ('valider_inscription', 'Valider une candidature'), ('valider_inscription_reconversion', 'Valider une candidature en programme Reconversion'), ('rejeter_inscription', 'Rejeter une candidature'), ('annuler_inscription', 'Annuler une inscription validée')], 'verbose_name': 'Inscription', 'verbose_name_plural': 'Inscriptions'},
        ),
        migrations.AddField(
            model_name='inscription',
            name='annule_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_annulees', to=settings.AUTH_USER_MODEL, verbose_name='Annulée par'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='date_annulation',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de l'annulation"),
        ),
        migrations.AddField(
            model_name='inscription',
            name='motif_annulation',
            field=models.TextField(blank=True, null=True, verbose_name="Motif de l'annulation"),
        ),
    ]
