# Generated by Django 6.1 on 2026-10-05 00:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0064_retrait_gerer_programmations_frais_par_defaut'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceJointeHebergement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_piece', models.CharField(max_length=225, verbose_name='Libellé de la pièce')),
                ('type_piece', models.CharField(choices=[('type_1', 'CNIB'), ('type_2', 'BULLETIN'), ('type_3', 'PHOTO'), ('type_4', 'Identification'), ('type_5', 'Diplome/Attestation')], default='type_1', max_length=30, verbose_name='Type de pièce')),
                ('est_requis', models.BooleanField(default=True, verbose_name='Obligatoire')),
                ('hebergement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_requises', to='courses.hebergement', verbose_name='Hébergement')),
            ],
            options={
                'verbose_name': 'Pièce à fournir (hébergement)',
                'verbose_name_plural': 'Pièces à fournir (hébergement)',
            },
        ),
        migrations.CreateModel(
            name='DocumentHebergement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece', models.FileField(blank=True, null=True, upload_to='hebergements/pieces', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Fichier')),
                ('date_depot', models.DateTimeField(auto_now_add=True, verbose_name='Date de dépôt')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='courses.demandehebergement', verbose_name='Demande')),
                ('piece_requise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.piecejointehebergement', verbose_name='Pièce demandée')),
            ],
            options={
                'verbose_name': "Document d'hébergement",
                'verbose_name_plural': "Documents d'hébergement",
            },
        ),
    ]
