# Generated by Django 6.1 on 2026-10-08 17:07

import django.db.models.deletion
from django.db import migrations, models


def initialiser_centre_encaissement(apps, schema_editor):
    """Remplit centre_encaissement pour les paiements existants : même règle
    qu'à la création (voir Paiement.deriver_centre_encaisseur) — le centre de
    l'agent qui a encaissé s'il est rattaché à un seul centre, sinon celui de
    l'inscription de l'apprenant, comme c'était implicitement le cas avant ce
    changement."""
    Paiement = apps.get_model('courses', 'Paiement')
    MembreAdministration = apps.get_model('accounts', 'MembreAdministration')

    structure_par_membre = dict(
        MembreAdministration.objects.exclude(structure__isnull=True).values_list('utilisateur_ptr_id', 'structure_id')
    )

    paiements = Paiement.objects.select_related(
        'dette__inscription__formation'
    ).filter(centre_encaissement__isnull=True)
    a_mettre_a_jour = []
    for paiement in paiements:
        centre_id = structure_par_membre.get(paiement.cree_par_id)
        if centre_id is None:
            dette = paiement.dette
            if dette and dette.inscription and dette.inscription.formation:
                centre_id = dette.inscription.formation.centre_id
        if centre_id is not None:
            paiement.centre_encaissement_id = centre_id
            a_mettre_a_jour.append(paiement)
    if a_mettre_a_jour:
        Paiement.objects.bulk_update(a_mettre_a_jour, ['centre_encaissement'], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0065_piecejointehebergement_documenthebergement'),
        ('accounts', '0033_compteurmatricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='centre_encaissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_encaisses', to='courses.centreformation', verbose_name="Centre d'encaissement"),
        ),
        migrations.RunPython(initialiser_centre_encaissement, migrations.RunPython.noop),
    ]
