# Generated by Django 5.2.1 on 2026-08-14 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonneNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse e-mail')),
                ('actif', models.BooleanField(default=True, verbose_name='Abonnement actif')),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_desinscription', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Abonné à la newsletter',
                'verbose_name_plural': 'Abonnés à la newsletter',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Adresse de la page')),
                ('chapeau', models.CharField(help_text="Résumé affiché dans la liste et dans l'e-mail envoyé aux abonnés.", max_length=300, verbose_name='Chapeau')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='actualites/', verbose_name='Image')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publiee', 'Publiée')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('date_publication', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('abonnes_notifies', models.BooleanField(default=False, verbose_name='Abonnés déjà notifiés')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actualites', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-date_publication', '-date_creation'],
                'permissions': [('gerer_actualites', 'Créer/modifier/supprimer une actualité'), ('publier_actualite', 'Publier une actualité et notifier les abonnés'), ('gerer_newsletter', 'Consulter et gérer les abonnés à la newsletter')],
            },
        ),
    ]
