# Generated by Django 5.2.1 on 2026-08-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0002_seed_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnenewsletter',
            name='nb_echecs',
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Échecs d'envoi consécutifs"),
        ),
    ]
